apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-longhorn-manager
spec:
  action: pod-kill
  mode: fixed-percent
  value: "33"
  duration: "300s"
  selector:
    namespaces:
      - longhorn-system
    labelSelectors:
      app: longhorn-manager
  containerNames:
    - 'longhorn-manager'
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-csi-plugin
spec:
  action: pod-kill
  mode: fixed-percent
  value: "33"
  duration: "300s"
  selector:
    namespaces:
      - longhorn-system
    labelSelectors:
      app: longhorn-csi-plugin
  containerNames:
    - 'longhorn-csi-plugin'
    - 'longhorn-liveness-probe'
    - 'node-driver-registrar'

---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-instance-manager
spec:
  action: pod-kill
  mode: fixed-percent
  value: "33"
  duration: "300s"
  selector:
    namespaces:
      - longhorn-system
    labelSelectors:
      longhorn.io/component: instance-manager
  containerNames:
    - 'instance-manager'
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-engine-image
spec:
  action: pod-kill
  mode: fixed-percent
  value: "33"
  duration: "300s"
  selector:
    namespaces:
      - longhorn-system
    labelSelectors:
      longhorn.io/component: engine-image