apiVersion: v1
kind: Service
metadata:
  name: chaos-dashboard-rancher
  namespace: chaos-mesh
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 2333
  selector:
    app.kubernetes.io/component: chaos-dashboard
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/name: chaos-mesh
  sessionAffinity: None
  type: ClusterIP