- name: "Authenticate"
  ansible.builtin.uri:
    url: "https://{{ rancher_hostname }}/v3-public/localProviders/local?action=login"
    method: POST
    body_format: json
    body:
      username: "{{ rancher_username }}"
      password: "{{ rancher_password }}"
    validate_certs: false
    status_code: 201
    return_content: true
  ignore_errors: true
  register: login_response
  delegate_to: localhost


- name: "Get Cluster"
  ansible.builtin.uri:
    url: "https://{{ rancher_hostname }}/v3/clusters?name={{ cluster_name }}"
    headers:
      Authorization: Bearer {{ login_response.json.token }}
    method: GET
    validate_certs: false
    status_code: 200
  register: cluster_response
  when: login_response is succeeded


- name: "Get Kubeconfig"
  ansible.builtin.uri:
    url: "https://{{ rancher_hostname }}/v3/clusters/{{ cluster_response.json.data[0].id }}?action=generateKubeconfig"
    headers:
      Authorization: Bearer {{ login_response.json.token }}
    method: POST
    body_format: json
    body: {}
    validate_certs: false
    status_code: 200
  register: cluster_response_kubeconfig
  when: login_response is succeeded
  delegate_to: localhost

- name: "Save kubeconfig"
  ansible.builtin.copy:
    content: "{{ cluster_response_kubeconfig.json.config }}"
    dest: "{{ kubeconfig_path }}/{{ cluster_name }}.yaml"
    mode: '0600'
    force: true
  delegate_to: localhost
