- name: Configure controlplanes downstream cluster
  vars:
    rancher_hostname: rancher.work.lan
    rancher_username: admin
    rancher_password: "{{ lookup ('env', 'RANCHER_PASSWORD') }}"
    cluster_name: longhorn-cl1
    kubeconfig_path: ~/.kube
    node_type: controlplane
  hosts: longhorn-cl1-controlplanes
  ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: configure_downstream

- name: Configure workers downstream cluster
  vars:
    rancher_hostname: rancher.work.lan
    rancher_username: admin
    rancher_password: "{{ lookup ('env', 'RANCHER_PASSWORD') }}"
    cluster_name: longhorn-cl1
    kubeconfig_path: ~/.kube
    node_type: worker
  hosts: longhorn-cl1-workers
  ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: configure_downstream
