---
- name: Remove vm on proxmox
  vars:
    vms_name:
      - rancher-node1
      - rancher-node2
      - rancher-node3
    vms_id:
      - 111
      - 112
      - 113
    proxmox_user: "{{ lookup ('env', 'PROXMOX_USER') }}"
    proxmox_pass: "{{ lookup ('env', 'PROXMOX_PASSWORD') }}"
    proxmox_api_target: "192.168.3.106:8006"
    proxmox_nodes:
      - proxmox-1
      - proxmox-2
      - proxmox-3

  hosts: localhost
  tasks:
    - name: Stop VM
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_target }}"
        name: "{{ item.0 }}"
        node: "{{ item.1 }}"
        state: stopped
        timeout: 300
      loop: "{{ vms_name | zip(proxmox_nodes ) | list }}"

    - name: Delete VM
      community.general.proxmox_kvm:
        node: "{{ item.1 }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_target }}"
        vmid: "{{ item.0 }}"
        state: absent
      loop: "{{ vms_id | zip(proxmox_nodes ) | list  }}"
